version: '2'
services:
  wordpress:
    build: .
    volumes:
      - ./wp-content:/var/www/wp-content
    env_file: .env
    ports:
      - "80:80"
    links:
      - mysql
      - redis
  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    command: crond -f -l 6 -L /dev/stdout
    volumes:
      - ./wp-content:/var/www/wp-content
      - ./mysqldumps:/usr/local/mysql
    env_file: .env
    links:
      - mysql
      - redis
  mysql:
    build:
       context: .
       dockerfile: Dockerfile-mysql 
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqldumps:/usr/local/mysql
    env_file: .env-mysql
  redis:
    image: redis:3.2.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
